# This is really just an example, nearly every field needs to be altered, you might just consider using the GUI
alias: Wish Child A a magical day
description: Wand trigger speech on homepod
trigger:
  - type: turned_on
    platform: device
    device_id: <some id>
    entity_id: <some id>
    domain: binary_sensor
  - type: turned_on
    platform: device
    device_id: <some id>
    entity_id: <some id>
    domain: binary_sensor
condition: []
action:
  - service: media_player.play_media
    target:
      entity_id: media_player.kitchen
    data:
      media_content_id: >-
        media-source://tts/google_translate?message=Hello+Child+A%2C+I+hope+you+are+having+a+magical+day%21&language=en-us
      media_content_type: provider
    metadata:
      title: Hello Child A, I hope you are having a magical day!
      thumbnail: https://brands.home-assistant.io/_/google_translate/logo.png
      media_class: app
      children_media_class: null
      navigateIds:
        - {}
        - media_content_type: app
          media_content_id: media-source://tts
        - media_content_type: provider
          media_content_id: >-
            media-source://tts/google_translate?message=Hello+Child+A%2C+I+hope+you+are+having+a+magical+day%21&language=en-us
mode: single
